CREATE DATABASE IF NOT EXISTS WEYE DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
USE WEYE;
DROP TABLE IF EXISTS COMPUTE_RULE;
CREATE TABLE IF NOT EXISTS COMPUTE_RULE
(
    ID           INT PRIMARY KEY AUTO_INCREMENT,
    NAME         VARCHAR(255) NOT NULL,
    SOURCE_TYPE  VARCHAR(255) NOT NULL,
    SOURCE_ID    INT          NOT NULL,
    FILTER_ITEM  VARCHAR(255),
    FILTER_OP    VARCHAR(255),
    FILTER_VALUE VARCHAR(255),
    ITEM         VARCHAR(255) NOT NULL,
    OP           VARCHAR(255) NOT NULL,
    TIME         INT          NOT NULL,
    TIME_UNIT    VARCHAR(255) NOT NULL,
    WEB_APP_ID   INT          NOT NULL
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8;