CREATE DATABASE IF NOT EXISTS WEYE DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
USE WEYE;
DROP TABLE IF EXISTS MONITOR_RULE;
CREATE TABLE IF NOT EXISTS MONITOR_RULE
(
    ID               INT PRIMARY KEY AUTO_INCREMENT,
    NAME             VARCHAR(255) NOT NULL,
    SOURCE_TYPE      VARCHAR(255) NOT NULL,
    SOURCE_ID        INT          NOT NULL,
    ITEM             VARCHAR(255) NOT NULL,
    CHART_TYPE       VARCHAR(255) NOT NULL,
    OUTPUT_DATA_NAME VARCHAR(255) DEFAULT 'data',
    WEB_APP_ID       INT          NOT NULL
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8;