CREATE DATABASE IF NOT EXISTS WEYE DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
USE WEYE;
DROP TABLE IF EXISTS COMPUTE_RECORD;
CREATE TABLE IF NOT EXISTS COMPUTE_RECORD
(
    ID              INT PRIMARY KEY AUTO_INCREMENT,
    COMPUTE_RULE_ID INT       NOT NULL,
    DATA            DOUBLE    NOT NULL,
    TIMESTAMP       TIMESTAMP NOT NULL
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8;