CREATE DATABASE IF NOT EXISTS WEYE DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
USE WEYE;
DROP TABLE IF EXISTS CUSTOM_COMMAND_COLLECTOR_RECORD;
CREATE TABLE IF NOT EXISTS CUSTOM_COMMAND_COLLECTOR_RECORD
(
    ID                          INT PRIMARY KEY AUTO_INCREMENT,
    SUBSCRIBE_ID INT       NOT NULL,
    DATA                        DOUBLE    NOT NULL,
    TIMESTAMP                   TIMESTAMP NOT NULL
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8;