CREATE DATABASE IF NOT EXISTS WEYE DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
USE WEYE;
DROP TABLE IF EXISTS HTTP_REQUEST_HEADER;
CREATE TABLE IF NOT EXISTS HTTP_REQUEST_HEADER
(
    ID                               INT PRIMARY KEY AUTO_INCREMENT,
    HTTP_REQUEST_COLLECTOR_RECORD_ID INT          NOT NULL,
    HEADER_NAME                      VARCHAR(255) NOT NULL,
    HEADER_VALUE                     VARCHAR(255) NOT NULL
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8;