CREATE DATABASE IF NOT EXISTS WEYE DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
USE WEYE;
DROP TABLE IF EXISTS HTTP_REQUEST_COLLECTOR_RECORD;
CREATE TABLE IF NOT EXISTS HTTP_REQUEST_COLLECTOR_RECORD
(
    ID             INT PRIMARY KEY AUTO_INCREMENT,
    WEB_APP_ID     INTEGER      NOT NULL,
    REQUEST_URL    VARCHAR(255) NOT NULL,
    REQUEST_METHOD VARCHAR(255) NOT NULL,
    REQUEST_IP     VARCHAR(255) NOT NULL,
    SRC_PORT       INTEGER      NOT NULL,
    HTTP_VERSION   VARCHAR(255) NOT NULL,
    TIMESTAMP      TIMESTAMP    NOT NULL
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8;