CREATE DATABASE IF NOT EXISTS WEYE DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
USE WEYE;
DROP TABLE IF EXISTS SERVER_COLLECTOR_RECORD;
CREATE TABLE IF NOT EXISTS SERVER_COLLECTOR_RECORD
(
    ID               INT PRIMARY KEY AUTO_INCREMENT,
    SERVER_ID        INT       NOT NULL,
    CPU_USAGE        DOUBLE,
    MEM_USAGE        DOUBLE,
    THREAD_COUNT     INT,
    CPU_TEMPERATURE  DOUBLE,
    CONTEXT_SWITCHES LONG,
    INTERRUPTS       LONG,
    RECV_SPEED       LONG,
    SEND_SPEED       LONG,
    TIMESTAMP        TIMESTAMP NOT NULL
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8;