CREATE DATABASE IF NOT EXISTS WEYE DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
USE WEYE;
DROP TABLE IF EXISTS WARN_RECORD;
CREATE TABLE IF NOT EXISTS WARN_RECORD
(
    ID           INT PRIMARY KEY AUTO_INCREMENT,
    WARN_RULE_ID INT       NOT NULL,
    RECORD_ID    INT       NOT NULL,
    STATUS       INT DEFAULT 0,
    TIMESTAMP    TIMESTAMP NOT NULL
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8;