CREATE DATABASE IF NOT EXISTS WEYE DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
USE WEYE;
DROP TABLE IF EXISTS CUSTOM_COMMAND;
CREATE TABLE IF NOT EXISTS CUSTOM_COMMAND
(
    ID        INT PRIMARY KEY AUTO_INCREMENT,
    NAME      VARCHAR(255) NOT NULL,
    COMMAND   VARCHAR(255) NOT NULL,
    DURATION  VARCHAR(255) NOT NULL
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8;