CREATE DATABASE IF NOT EXISTS WEYE DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
USE WEYE;
DROP TABLE IF EXISTS CUSTOM_COMMAND_SUBSCRIBE;
CREATE TABLE IF NOT EXISTS CUSTOM_COMMAND_SUBSCRIBE
(
    ID                INT PRIMARY KEY AUTO_INCREMENT,
    WEB_APP_ID        INTEGER NOT NULL,
    CUSTOM_COMMAND_ID INTEGER NOT NULL
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8;