CREATE DATABASE IF NOT EXISTS WEYE DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
USE WEYE;
DROP TABLE IF EXISTS SERVER;
CREATE TABLE IF NOT EXISTS SERVER
(
    ID           INT PRIMARY KEY AUTO_INCREMENT,
    NAME         VARCHAR(255) NOT NULL,
    IP           VARCHAR(255) NOT NULL UNIQUE,
    AGENT_STATUS INTEGER DEFAULT 3,
    API_KEY      VARCHAR(255) NOT NULL UNIQUE
) ENGINE = INNODB
  DEFAULT CHARSET = UTF8;